export const APP_NAME = 'SecureVote'

export const ROUTES = {
  // ── Social ─────────────────────────────────────────────────────────────────
  social:                   '/social',
  adminSocial:              '/admin/social',
  adminSocialModeration:    '/admin/social-moderation',
  creatorSocial:            '/elections/social',
  voterSocial:              '/voter/social',
  socialCreate:             '/social/create',
  socialPost:               (id: string) => `/social/posts/${id}`,
  socialProfile:            (username: string) => `/social/profile/${username}`,
  socialHashtag:            (tag: string) => `/social/hashtag/${tag}`,
  socialSearch:             '/social/search',
  socialNotifications:      '/social/notifications',
  socialBookmarks:          '/social/bookmarks',
  socialDrafts:             '/social/drafts',
  socialFollowing:          '/social/following',
  socialTrending:           '/social/trending',
  socialNews:               '/social/news',
  landing:                  '/landing',
  communityFeed:            '/social',
  // ── Existing ───────────────────────────────────────────────────────────────
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/auth/forgot-password',
  resetPassword: '/auth/reset-password',
  verifyEmail: '/auth/verify-email',
  accountCreatorStatus: '/account/creator-status',
  dashboard: '/dashboard',
  elections: '/elections',
  creatorDashboard: '/elections/creator',
  electionWizardNew: '/elections/wizard',
  electionWizard: (id: string) => `/elections/${id}/wizard`,
  electionNew: '/elections/new',
  electionDetail: (id: string) => `/elections/${id}`,
  electionEdit: (id: string) => `/elections/${id}/edit`,
  electionCreatorView: (id: string) => `/elections/${id}/creator-view`,
  electionCandidates: (id: string) => `/elections/${id}/candidates`,
  electionCandidatePreview: (electionId: string, candidateId: string) =>
    `/elections/${electionId}/candidates/${candidateId}`,
  electionVote: (id: string) => `/elections/${id}/vote`,
  electionResults: (id: string) => `/elections/${id}/results`,
  electionsManage: '/elections/manage',
  creatorAnalytics: '/elections/analytics',
  myVotes: '/my-votes',
  admin: '/admin',
  adminElections: '/admin/elections',
  adminElectionManage: (id: string) => `/admin/elections/${id}/manage`,
  adminCreators: '/admin/creators',
  adminApprovals: '/admin/approvals',
  adminAudit: '/admin/audit',
  adminUsers: '/admin/users',
  notifications: '/notifications',
  settings: '/settings',
} as const
